# Generated by Django 3.0.4 on 2020-04-07 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=4000)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 8, 55, 15, 976851, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordsGenerationMethods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordsGenerationResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 8, 55, 15, 978076, tzinfo=utc))),
                ('id_example', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='keywords.Example')),
                ('id_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='keywords.KeyWordsGenerationMethods')),
            ],
        ),
    ]
