# Generated by Django 3.0.4 on 2020-04-07 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 9, 0, 28, 826910, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='example',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keywordsgenerationmethods',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keywordsgenerationresults',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 9, 0, 28, 827997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keywordsgenerationresults',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
