# Generated by Django 3.0.4 on 2020-04-08 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_auto_20200407_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordsgenerationresults',
            name='created',
        ),
        migrations.RemoveField(
            model_name='keywordsgenerationresults',
            name='id_example',
        ),
        migrations.RemoveField(
            model_name='keywordsgenerationresults',
            name='id_method',
        ),
        migrations.AlterField(
            model_name='example',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 9, 58, 13, 279603, tzinfo=utc)),
        ),
    ]
